fargate_final:
  outputs:
    dev:
      account: kra58564.us-east-1
      database: FARGATE
      password: UsFa@2022
      role: RL_FARGATE
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: USER_FARGATE
      warehouse: WH_FARGATE
  target: dev